# Generated by Django 5.0.2 on 2024-03-03 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceGuide', '0002_alter_transaction_equip_equip_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='category',
            field=models.CharField(choices=[('E', 'Equipment'), ('U', 'Use'), ('S', 'Set-up'), ('T', 'Etc'), ('N', 'NX')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='ACC',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='Avoid',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='DEX',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='INT',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='LUK',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='Matt',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='STR',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='att',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
    ]
