# Generated by Django 5.0.2 on 2024-03-04 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceGuide', '0003_alter_stuff_category_alter_transaction_equip_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_equip',
            name='is_clean',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='DEX',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='INT',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='LUK',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='STR',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='slot',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.CreateModel(
            name='equipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STR', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('DEX', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('INT', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)])),
                ('LUK', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200)])),
                ('ACC', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)])),
                ('Avoid', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150)])),
                ('att', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250)])),
                ('Matt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)])),
                ('slot', models.PositiveIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(100)])),
                ('equip_name', models.ForeignKey(limit_choices_to={'category': 'E'}, on_delete=django.db.models.deletion.CASCADE, to='priceGuide.stuff', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction_equip',
            name='equip_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priceGuide.equipinfo'),
        ),
    ]
